alertmanager:
  enabled: false

pushgateway:
  enabled: false

server:
  global:
    scrape_interval: 10s
  persistentVolume:
    storageClass: gp2
  statefulSet:
    enabled: true
    headless:
      servicePort: 9090

  service:
    servicePort: 9090

kubeStateMetrics:
  service:
    servicePort: 8080
