name: Build and release
on:
  push:
    branches:
      - master
    paths:
      - '**.tf'
      - '**.yaml'

jobs:
  release:
    runs-on: ubuntu-latest
    name: Release
    steps:
      - name: "Git: Checkout master with full history"
        uses: actions/checkout@master
        with:
          fetch-depth: 0

      - name: "Git: Configure local settings"
        run: |
          git config --local user.email "action@github.com"
          git config --local user.name "GitHub Action"

      - name: "Setup: Calculate next version number"
        uses: mathieudutour/github-tag-action@v4.1
        id: version
        with:
          tag_prefix: ""
          dry_run: true
          default_bump: patch
          github_token: ${{ secrets.GITHUB_TOKEN }}

      - name: "Changelog: Create full changelog for commit"
        uses: nuuday/github-changelog-action@master
        with:
          next_version: ${{ steps.version.outputs.new_version }}

      - name: "Git: Commit changed files and tag release"
        run: |
          git add CHANGELOG.md
          git commit -m"Changelog updated" CHANGELOG.md
          git tag -m"$Tagged new version: ${{ steps.version.outputs.new_version }}" -fa ${{ steps.version.outputs.new_tag }}
          git push --tags

      - name: "Changelog: Create changelog for release"
        uses: nuuday/github-changelog-action@master
        id: changelog
        with:
          filename: null
          tag: ${{ steps.version.outputs.new_tag }}

      - name: "Github: Create release"
        uses: actions/create-release@v1
        id: release
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
        with:
          tag_name: ${{ steps.version.outputs.new_tag }}
          release_name: Release ${{ steps.version.outputs.new_version }}
          draft: false
          prerelease: false
          body: ${{ steps.changelog.outputs.changelog }}

